[sources.json_logs]
type = "docker_logs"
include_containers = ["vector.parser=json"]

[transforms.json_output]
type = "remap"
inputs = ["json_logs"]
drop_on_abort = false
source = """
del(.container_id)
del(.label)
del(.source_type)

.message = parse_json!(.message)

.level = .message.level
del(.message.level)
"""

[sinks.json_loki]
type = "loki"
inputs = ["json_output"]
endpoint = "${LOKI_ENDPOINT:?must set LOKI_ENDPOINT in env}"
encoding.codec = "json"

[sinks.json_loki.labels]
source = "json"
container = "{{ .container_name }}"
image = "{{ .image }}"
stream = "{{ .stream }}"
level = "{{ .level }}"